import raw from './problems.json';
import type { Problem, TestCase } from '../types';

/** Generated by `python3 data/build.py`. */
export const PROBLEMS = raw as unknown as Problem[];

export const BY_ID: ReadonlyMap<string, Problem> = new Map(PROBLEMS.map((p) => [p.id, p]));

export const TOPICS: string[] = Array.from(new Set(PROBLEMS.map((p) => p.topic))).sort();

const testFiles = import.meta.glob<TestCase[]>('./tests/*.json', { import: 'default' });

const cache = new Map<string, Promise<TestCase[]>>();

/** All test cases of a problem (including hidden and large ones). Each set loads once, on demand. */
export function loadTests(id: string): Promise<TestCase[]> {
  let hit = cache.get(id);
  if (!hit) {
    const loader = testFiles[`./tests/${id}.json`];
    hit = loader ? loader() : Promise.reject(new Error(`No test data for ${id}`));
    hit.catch(() => cache.delete(id));
    cache.set(id, hit);
  }
  return hit;
}
